# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Android Jam 2"
  description: "GDG Aracaju Study Jam 2016"
  date: "Março a Abril/2016"
  price: "Em breve"
  address: ""
  venue: ""
  city: "Aracaju"

# Site info
site:
  url: "http://android.gdgaracaju.com.br"
  favicon: "http://www.gdgaracaju.com.br/favicon.ico"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "./img/covers/android-background.jpg"
    facebook: "http://android.gdgaracaju.com.br/img/covers/android-background.jpg"

subscribe_text: "Acesse o GDG Aracaju"
subscribe_url: "http://site.gdgaracaju.com.br/"

# Active sections on the website
sections:
  about: true
  c4p: true
  location: false
  speakers: false
  schedule: false
  sponsors: false
  partners: true
  contact: true
  tickets: false

# Speakers list
speakers:
  -
    name: "Erick Mendonça"
    photo: "./img/speakers/erick_mendonca.jpg"
    bio: "Formando na Universidade Federal de Sergipe e possui experiência como desenvolvedor e analista de sistemas. Co-organizador do Google Developer Group Aracaju, busca compartilhar conhecimento e aperfeiçoar a comunidade local de desenvolvedores e empreendedores através de eventos técnicos e encontros descontraídos para incentivar o crescimento e a empatia da comunidade local."
    company: "UFS"
    plus: "+ErickMendonca"
    presentations:
      - 
        title: "Revisão do Android Fundamentals"
        description: ""
        time: "--"

# Schedule
schedule:
  - 
    name: "Android Fundamentals Review"
    time: 14h00
    description: "Revisão do conteúdo do curso Android Fundamentals"
  - 
    name: "Palestra #1"
    time: 14h30
    description: "Primeira palestra do dia."
  - 
    name: "Coffee-break"
    time: 16h00
    description: "Coma, beba e faça networking."
  - 
    name: "Palestra #2"
    time: 16h30
    description: "Segunda palestra do dia."
  - 
    name: "Pós-evento"
    time: 18h00
    description: "Dúvidas, conversa, networking."


# List of Sponsors
sponsors:
  #-
  #  name: "Eventick"
  #  logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
  #  url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "CajuValley"
    logo: "./img/partners/cajuvalley.png"
    url: "https://www.facebook.com/cajuvalley"
  -
    name: "Getinfo"
    logo: "./img/partners/getinfo.png"
    url: "http://getinfo.net.br/"
  -
    name: "GDG Aracaju"
    logo: "./img/partners/gdgaracaju.png"
    url: "http://www.gdgaracaju.com.br/"
  -
    name: "DP Sistemas"
    logo: "./img/partners/dpsistemas.png"
    url: "http://www2.dpsistemas.com.br/"


# About section
about_section:
   title: "Sobre"
   description: "" #moved to ./includes/section/about.md

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Se você tem interesse em contribuir com a comunidade nessa jornada, faça uma proposta :) Nós estamos interessados em testes, Firebase, aplicativos híbridos, criação de APIs, backend,, além de conteúdo sobre desenvolvimento Android."
   c4p_url: "http://goo.gl/forms/SCg7LyBTi7"
   c4p_caption: "Preencha o form!"
   c4p_rules_url: ""
   c4p_rules_caption: ""

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"

# Schedule section
schedule_section:
   title: "Programação"
   text: "A programação pode sofrer alterações sem avisos prévios."
   time: "Hora"
   slot: "Atividade"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"
