# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Android Jam"
  description: "GDG Aracaju Study Jam"
  date: "Fevereiro a Março/2015"
  price: "A partir de R$ 15,00"
  address: "Av. Desembargador Maynard, 142"
  venue: "DP Sistemas"
  city: "Aracaju"

# Site info
site:
  url: "http://android.gdgaracaju.com.br"
  favicon: "http://www.gdgaracaju.com.br/favicon.ico"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "./img/android_garden.jpg"
    facebook: "http://android.gdgaracaju.com.br/img/studyjam_assets/01.png"

subscribe_text: "Inscrições abertas!"
subscribe_url: "http://www.eventick.com.br/android-jam-sergipe-1"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: true
  schedule: false
  sponsors: true
  partners: true
  contact: true
  tickets: true

# The entire schedule
schedule:
  #-
  #  name: "Check-in / Breakfast"
  #  time: "9h00"
  -
    name: "Erick Mendonça"
    photo: "./img/speakers/erick_mendonca.jpg"
    bio: "Formando na Universidade Federal de Sergipe e possui experiência como desenvolvedor e analista de sistemas. Co-organizador do Google Developer Group Aracaju, busca compartilhar conhecimento e aperfeiçoar a comunidade local de desenvolvedores e empreendedores através de eventos técnicos e encontros descontraídos para incentivar o crescimento e a empatia da comunidade local."
    company: "UFS"
    plus: "+ErickMendonca"
    presentation:
      title: "Começando o desenvolvimento de aplicativos Android"
      description: ""
      time: "07/02"
  -
    name: "Lucas Xavier"
    photo: "./img/speakers/lucas_xavier.jpg"
    bio: ""
    company: ""
    plus: "+LucasXavierAS"
    presentation:
      title: "Construindo aplicativos Android de alto desempenho"
      description: ""
      time: "07/02"
  -
    name: "Breno Moura"
    photo: "./img/speakers/breno_moura.jpg"
    bio: "Entusiasta Ruby e desenvolvedor Ruby e Ruby on Rails há 2 anos, Breno atualmente desenvolve aplicações back end e apis de integração na Jaya Apps."
    company: "Jaya Apps"
    plus: "+BrenoMoura27"
    presentation:
      title: "Criando APIs com Rails"
      description: ""
      time: "21/02"
  -
    name: "Ítalo Marcel"
    photo: "./img/speakers/italo_marcel.jpg"
    bio: "Um gamer nato e apaixonado por Android, formado em Programação de Sistemas pelo Instituto Federal de Sergipe e graduando em Ciência da Computação pela Universidade Federal de Sergipe. Programa desde os 15 anos de idade, e já desenvolveu diversos aplicativos durante os mais de 4 anos como engenheiro Android. Inovar faz parte de seu DNA."
    company: "Getinfo"
    plus: "+ItaloMarcel"
    presentation:
      title: "Material Design"
      description: ""
      time: "21/02"
  -
    name: "Euler Neto"
    photo: "./img/speakers/euler_neto.jpg"
    bio: ""
    company: "UFS"
    plus: "+EulerNetoNgt"
    presentation:
      title: "Segurança no Android"
      description: ""
      time: "07/03"
  -
    name: "Hugo Dória"
    photo: "./img/speakers/hugo_doria.jpg"
    bio: "Profissional com mais de seis anos de experiência em TI. DevOP por natureza. Desenvolvedor do Arch Linux e de diversos apps para dispositivos móveis, incluindo apps bancários, frameworks para conferências e força de vendas. Adora a arte de criar ótimas experiências no mobile, aliado a uma ótima trilha sonora. Pai, gamer e alguém que acredita num mundo melhor."
    company: "Popcode"
    plus: "106714577233715858252"
    presentation:
      title: "API-First: a 'Revolução Industrial' do software"
      description: ""
      time: "07/03"
  -
    name: "Roberto Brandini"
    photo: "./img/speakers/roberto_brandini.jpg"
    bio: ""
    company: "DP Sistemas"
    plus: "+RobertoBrandini"
    presentation:
      title: "Backend para aplicativos mobile"
      description: ""
      time: "21/03"

# List of Sponsors
sponsors:
  #-
  #  name: "Eventick"
  #  logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
  #  url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "CajuValley"
    logo: "./img/partners/cajuvalley.png"
    url: "https://www.facebook.com/cajuvalley"
  -
    name: "Getinfo"
    logo: "./img/partners/getinfo.png"
    url: "http://getinfo.net.br/"
  -
    name: "GDG Aracaju"
    logo: "./img/partners/gdgaracaju.png"
    url: "http://www.gdgaracaju.com.br/"
  -
    name: "DP Sistemas"
    logo: "./img/partners/dpsistemas.png"
    url: "http://www2.dpsistemas.com.br/"
  -
    name: "Popcode"
    logo: "./img/partners/popcode.jpg"
    url: "http://www.popcode.com.br/"


# About section
about_section:
   title: "Sobre"
   description: 
    - 
      p: "O GDG Aracaju convida todos os interessados na plataforma Android a estudar conosco e desenvolver aplicativos completos. Cada encontro será lotado de conteúdo e contará com palestras de profissionais convidados."
    - 
      p: "O Android Jam faz parte do Google Developers Study Jams, que é uma série global de eventos para formar grupos de estudos nas comunidades. A primeira sessão da iniciativa está sendo realizada em parceria com o Udacity e seguirá o curso Android Fundamentals da plataforma."
    - 
      p: "Reembolsos: se você não puder comparecer ao evento, você pode pedir reembolso até 5 dias antes do mesmo. Nós reembolsaremos o valor da entrada, deduzida das taxas do Eventick."
    -
      p: "Sem fins lucrativos: o Android Jam não possui fins lucrativos. Todo o dinheiro arrecadado será investido no coffee-break do evento."

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: " consequat."
   c4p_url: "http://call4paperz.com"
   c4p_caption: "Submit"
   c4p_rules_url: "http://call4paperz.com"
   c4p_rules_caption: "Read the rules."

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: true
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"

# Schedule section
schedule_section:
   title: "Programação"
   text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."
   time: "Time"
   slot: "Slot"
   description: "Description"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: true
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"