# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Android Jam"
  description: "GDG Aracaju Study Jam"
  date: "Fevereiro a Março/2015"
  price: ":-)"
  address: "Av. Desembargador Maynard, 142"
  venue: "DP Sistemas"
  city: "Aracaju"

# Site info
site:
  url: "http://android.gdgaracaju.com.br"
  favicon: "http://www.gdgaracaju.com.br/favicon.ico"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "./img/studyjam_assets/01.png"
    facebook: "./img/studyjam_assets/01.png"

subscribe_text: "Inscreva-se"
subscribe_url: "http://www.eventick.com.br/"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: true
  schedule: false
  sponsors: true
  partners: true
  contact: true

# The entire schedule
schedule:
  #-
  #  name: "Check-in / Breakfast"
  #  time: "9h00"
  -
    name: "Breno Moura"
    photo: "./img/speakers/breno_moura.jpg"
    bio: ""
    company: "Jaya Apps"
    twitter: ""
    presentation:
      title: "Criando APIs com Rails"
      description: ""
      time: "--"
  -
    name: "Euler Neto"
    photo: "./img/speakers/euler_neto.jpg"
    bio: ""
    company: "UFS"
    twitter: ""
    presentation:
      title: "Segurança no Android"
      description: ""
      time: "--"
  -
    name: "Erick Mendonça"
    photo: "./img/speakers/erick_mendonca.jpg"
    bio: ""
    company: "UFS"
    twitter: "erickmagnus"
    presentation:
      title: "Começando o desenvolvimento de aplicativos Android"
      description: ""
      time: "07/02"
  -
    name: "Hugo Dória"
    photo: "./img/speakers/hugo_doria.jpg"
    bio: ""
    company: "Popcode"
    twitter: ""
    presentation:
      title: "API-First"
      description: ""
      time: "--"
  -
    name: "Ítalo Marcel"
    photo: "./img/speakers/italo_marcel.jpg"
    bio: ""
    company: "Getinfo"
    twitter: ""
    presentation:
      title: "Material Design"
      description: ""
      time: "--"
  -
    name: "Lucas Xavier"
    photo: "./img/speakers/lucas_xavier.jpg"
    bio: ""
    company: ""
    twitter: ""
    presentation:
      title: "Construindo apps Android de Alto Desempenho"
      description: ""
      time: "--"
  -
    name: "Roberto Brandini"
    photo: "./img/speakers/roberto_brandini.jpg"
    bio: ""
    company: "DP Sistemas"
    twitter: ""
    presentation:
      title: "Backend para aplicativos mobile"
      description: ""
      time: "--"

# List of Sponsors
sponsors:
  #-
  #  name: "Eventick"
  #  logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
  #  url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "CajuValley"
    logo: "./img/partners/cajuvalley.png"
    url: "https://www.facebook.com/cajuvalley"
  -
    name: "GDG Aracaju"
    logo: "./img/partners/gdgaracaju.png"
    url: "https://www.gdgaracaju.com.br/"
  -
    name: "DP Sistemas"
    logo: "./img/partners/dpsistemas.png"
    url: "https://www.dpsistemas.com.br/"

# About section
about_section:
   title: "Sobre"
   description: 
    - 
      p: "O Android Jam faz parte do Google Developers Study Jams, que é uma série global de eventos para formar grupos de estudos nas comunidades. A primeira sessão da iniciativa está sendo realizada em parceria com o Udacity e seguirá o curso Android Fundamentals da plataforma"
    - 
      p: "Nós do GDG Aracaju estamos convidando todos os interessados na plataforma Android para estudar conosco e desenvolver aplicativos completos. Cada encontro será lotado de conteúdo e contará também com uma palestra de um profissional convidado."

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: " consequat."
   c4p_url: "http://call4paperz.com"
   c4p_caption: "Submit"
   c4p_rules_url: "http://call4paperz.com"
   c4p_rules_caption: "Read the rules."

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: true

# Schedule section
schedule_section:
   title: "Programação"
   text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."
   time: "Time"
   slot: "Slot"
   description: "Description"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: true